### PR TITLE
Add smart mirror to projects

### PR DESCRIPTION
**Pull request by evancohen**
- [X] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [X] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
	- [X] includes a valid (https) link,
	- [X] includes a concise and on-topic description,
	- [X] mentions if there is only support some devices,
	- [X] is not a duplicate,
	- [X] has been added at the bottom of the appropriate category,
	- [X] is in the form of **Named Link - Description, seperated by commas.**
	- [X] ends with a dot.

### CODE REVIEW

**Comment by evancohen** [comment]
Right on 👍 
Thanks for maintaining this list!

**Comment by jtyle6** [comment]
What about this project? https://magicmirror.builders/

**Comment by evancohen** [comment]
+1 for also including Michael's project!

**Comment by thibmaek** [comment]
@jtyle6 looks cool as well! I'd love it if you could make a seperate PR for this so I can add it in 🙂

**Comment by jtyle6** [comment]
@thibmaek whoops sorry didn't check this for a few days.

**Pull request merged**
